spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}

jwt:
  secret: ${JWT_SECRET_KEY}

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}

apple:
  team-id: ${APPLE_TEAM_ID}
  client-id: ${APPLE_CLIENT_ID}
  key-id: ${APPLE_KEY_ID}
  private-key-path: ${APPLE_PRIVATE_KEY_PATH}
  redirect-uri: ${APPLE_REDIRECT_URI}
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

encrypt:
  aes:
    key: ${AES_ENCRYPTION_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health

bedrock:
  region: ${BEDROCK_REGION}
  modelId: ${BEDROCK_MODEL_ID}
  timeout:
    connectMs: ${BEDROCK_CONNECT_MS}
    responseMs: ${BEDROCK_RESPONSE_MS}
    apiCallMs: ${BEDROCK_APICALL_MS}
aws:
  bedrock:
    api-key: ${AWS_BEARER_TOKEN_BEDROCK:}